from PyQt5.QtWidgets import QApplication

from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QFont, QPalette, QColor

QApplication.setStyle("Fusion")

app = QApplication.instance()
if app:
    # 폰트 설정
    font = QFont("Segoe UI", 10)  # 윈도우에서 가독성이 좋은 폰트
    app.setFont(font)

    # 다크 모드 팔레트 설정
    palette = QPalette()
    palette.setColor(QPalette.Window, QColor(53, 53, 53))  # 다크 배경
    palette.setColor(QPalette.WindowText, QColor(255, 255, 255))  # 흰색 글자
    palette.setColor(QPalette.Base, QColor(35, 35, 35))  # 입력창 배경
    palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    palette.setColor(QPalette.ToolTipBase, QColor(255, 255, 220))
    palette.setColor(QPalette.ToolTipText, QColor(0, 0, 0))
    palette.setColor(QPalette.Text, QColor(255, 255, 255))
    palette.setColor(QPalette.Button, QColor(53, 53, 53))
    palette.setColor(QPalette.ButtonText, QColor(255, 255, 255))
    palette.setColor(QPalette.BrightText, QColor(255, 0, 0))
    palette.setColor(QPalette.Highlight, QColor(142, 45, 197))  # 강조 색상
    palette.setColor(QPalette.HighlightedText, QColor(0, 0, 0))
    app.setPalette(palette)

    # 기본 스타일시트 적용 (버튼, 입력창 등)
    app.setStyleSheet("""
        QWidget {
            background-color: #353535;
            color: #ffffff;
        }
        QPushButton {
            background-color: #2c3e50;
            border: 1px solid #1a252f;
            padding: 5px;
            border-radius: 3px;
        }
        QPushButton:hover {
            background-color: #1a252f;
        }
        QLineEdit {
            background-color: #1e1e1e;
            border: 1px solid #5a5a5a;
            padding: 4px;
            color: white;
        }
        QLabel {
            font-size: 12px;
            font-weight: bold;
        }
    """)
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/yhk/Library/CloudStorage/OneDrive-postech.ac.kr/Python/SAXS_InSitu_Contour_Corrector/contour_main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1883, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SW_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.SW_main.setObjectName("SW_main")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.LE_spec_log_dir = QtWidgets.QLineEdit(self.frame)
        self.LE_spec_log_dir.setObjectName("LE_spec_log_dir")
        self.horizontalLayout.addWidget(self.LE_spec_log_dir)
        self.PB_spec_log_browse = QtWidgets.QPushButton(self.frame)
        self.PB_spec_log_browse.setObjectName("PB_spec_log_browse")
        self.horizontalLayout.addWidget(self.PB_spec_log_browse)
        self.PB_spec_apply = QtWidgets.QPushButton(self.frame)
        self.PB_spec_apply.setObjectName("PB_spec_apply")
        self.horizontalLayout.addWidget(self.PB_spec_apply)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.LE_dat_dir = QtWidgets.QLineEdit(self.frame_2)
        self.LE_dat_dir.setObjectName("LE_dat_dir")
        self.horizontalLayout_2.addWidget(self.LE_dat_dir)
        self.PB_dat_browse = QtWidgets.QPushButton(self.frame_2)
        self.PB_dat_browse.setObjectName("PB_dat_browse")
        self.horizontalLayout_2.addWidget(self.PB_dat_browse)
        self.PB_dat_apply = QtWidgets.QPushButton(self.frame_2)
        self.PB_dat_apply.setObjectName("PB_dat_apply")
        self.horizontalLayout_2.addWidget(self.PB_dat_apply)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.LE_output_dir = QtWidgets.QLineEdit(self.frame_3)
        self.LE_output_dir.setObjectName("LE_output_dir")
        self.horizontalLayout_3.addWidget(self.LE_output_dir)
        self.PB_output_browse = QtWidgets.QPushButton(self.frame_3)
        self.PB_output_browse.setObjectName("PB_output_browse")
        self.horizontalLayout_3.addWidget(self.PB_output_browse)
        self.PB_output_apply = QtWidgets.QPushButton(self.frame_3)
        self.PB_output_apply.setObjectName("PB_output_apply")
        self.horizontalLayout_3.addWidget(self.PB_output_apply)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.TW_Process_List = QtWidgets.QTableWidget(self.frame_9)
        self.TW_Process_List.setObjectName("TW_Process_List")
        self.TW_Process_List.setColumnCount(0)
        self.TW_Process_List.setRowCount(0)
        self.verticalLayout_2.addWidget(self.TW_Process_List)
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setIndent(6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(12, 12, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PB_reset = QtWidgets.QPushButton(self.frame_7)
        self.PB_reset.setObjectName("PB_reset")
        self.horizontalLayout_5.addWidget(self.PB_reset)
        self.PB_next_1 = QtWidgets.QPushButton(self.frame_7)
        self.PB_next_1.setObjectName("PB_next_1")
        self.horizontalLayout_5.addWidget(self.PB_next_1)
        self.horizontalLayout_6.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.SW_main.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.SW_main.addWidget(self.page_2)
        self.horizontalLayout_4.addWidget(self.SW_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SPEC log file"))
        self.PB_spec_log_browse.setText(_translate("MainWindow", "Browse"))
        self.PB_spec_apply.setText(_translate("MainWindow", "Apply"))
        self.label_2.setText(_translate("MainWindow", ".dat file"))
        self.PB_dat_browse.setText(_translate("MainWindow", "Browse"))
        self.PB_dat_apply.setText(_translate("MainWindow", "Apply"))
        self.label_3.setText(_translate("MainWindow", "Output"))
        self.PB_output_browse.setText(_translate("MainWindow", "Browse"))
        self.PB_output_apply.setText(_translate("MainWindow", "Apply"))
        self.label_6.setText(_translate("MainWindow", "Process File List"))
        self.label_4.setText(_translate("MainWindow", "Last Update: FEB, 2025"))
        self.label_5.setText(_translate("MainWindow", "hyungju@postech.ac.kr, yhkim26@postech.ac.kr"))
        self.label_11.setText(_translate("MainWindow", "9A Beamline, PAL"))
        self.PB_reset.setText(_translate("MainWindow", "Reset"))
        self.PB_next_1.setText(_translate("MainWindow", "Next"))
