from PyQt5.QtWidgets import QApplication

from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QFont, QPalette, QColor

QApplication.setStyle("Fusion")

app = QApplication.instance()
if app:
    # 폰트 설정
    font = QFont("Segoe UI", 10)  # 윈도우에서 가독성이 좋은 폰트
    app.setFont(font)

    # 다크 모드 팔레트 설정
    palette = QPalette()
    palette.setColor(QPalette.Window, QColor(53, 53, 53))  # 다크 배경
    palette.setColor(QPalette.WindowText, QColor(255, 255, 255))  # 흰색 글자
    palette.setColor(QPalette.Base, QColor(35, 35, 35))  # 입력창 배경
    palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    palette.setColor(QPalette.ToolTipBase, QColor(255, 255, 220))
    palette.setColor(QPalette.ToolTipText, QColor(0, 0, 0))
    palette.setColor(QPalette.Text, QColor(255, 255, 255))
    palette.setColor(QPalette.Button, QColor(53, 53, 53))
    palette.setColor(QPalette.ButtonText, QColor(255, 255, 255))
    palette.setColor(QPalette.BrightText, QColor(255, 0, 0))
    palette.setColor(QPalette.Highlight, QColor(142, 45, 197))  # 강조 색상
    palette.setColor(QPalette.HighlightedText, QColor(0, 0, 0))
    app.setPalette(palette)

    # 기본 스타일시트 적용 (버튼, 입력창 등)
    app.setStyleSheet("""
        QWidget {
            background-color: #353535;
            color: #ffffff;
        }
        QPushButton {
            background-color: #2c3e50;
            border: 1px solid #1a252f;
            padding: 5px;
            border-radius: 3px;
        }
        QPushButton:hover {
            background-color: #1a252f;
        }
        QLineEdit {
            background-color: #1e1e1e;
            border: 1px solid #5a5a5a;
            padding: 4px;
            color: white;
        }
        QLabel {
            font-size: 12px;
            font-weight: bold;
        }
    """)
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/yhk/Library/CloudStorage/OneDrive-postech.ac.kr/Python/SAXS_InSitu_Contour_Corrector/contour_peak_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Peak_export_manager(object):
    def setupUi(self, Peak_export_manager):
        Peak_export_manager.setObjectName("Peak_export_manager")
        Peak_export_manager.resize(1424, 807)

        self.retranslateUi(Peak_export_manager)
        QtCore.QMetaObject.connectSlotsByName(Peak_export_manager)

    def retranslateUi(self, Peak_export_manager):
        _translate = QtCore.QCoreApplication.translate
        Peak_export_manager.setWindowTitle(_translate("Peak_export_manager", "Peak Export Manager"))
